Comment: >
  The active loop parameters has the full experiment configs.
  Iteration_x shows the config for iteration number x.

  iteration_x:
    output_prev_run:  [""] # where the outputs of the last iteration are saved
    csv_file_prev_run: [""] # where the csv file of the last iteration is saved
    method: "random"  #active learning method
    num_frames: 10  # where the new frames are located
    iteration_folder: null

project: "ibl_toy"

active_pipeline:
  experiment_cfg: ${oc.env:LIGHTPOSE_DIR}/active_pipeline/configs/config_ibl_experiment.yaml
  iterations_folders: "{oc.env:LIGHTPOSE_DIR}/active_pipeline/results/iteration_active_loop/experiment0"
  start_iteration: 1
  end_iteration: 2
  current_iteration: null
  experiment_kwargs: null
  active_test_set_path: null

# select frames not yet available
iteration_0:
  output_prev_run: []
  csv_file_prev_run: []
  method: "random"
  num_frames: 10
  use_seeds: [0]
  iteration_folder: null

iteration_1:
  output_prev_run: []
  csv_file_prev_run: []
  method: "random"
  num_frames: 10
  use_seeds: [0]
  iteration_folder: null

iteration_2:
  output_prev_run: []
  method: "random"
  num_frames: 10
  use_seeds: [0]
  iteration_folder: null




