Comment: >
  # Example
  iteration_x:
    output_prev_run:  [""] # where the outputs of the last iteration are saved
    csv_file_prev_run: [""] # where the csv file of the last iteration is saved
    method: "random"  #active learning method
    num_frames: 10  # where the new frames are located
    iteration_folder: null

project: "active_mirror_mouse"

active_loop:
  experiment_cfg: "/content/lightning-pose/scripts/configs/config_mirror-mouse for_Haotian.yaml"
  iterations_folder: "iteration_active_loop/experiment0" #relative to data_dir
  fast_dev_run: 1
  start_iteration: 0
  end_iteration: 2
  current_iteration: null


iteration_0:
  output_prev_run: [""]
  csv_file_prev_run: [""]
  method: "random"
  num_frames: 10
  use_seeds: [0,1]
  iteration_folder: null

iteration_1:
  output_prev_run: [""] # example: ["/data/libraries/lightning-pose/outputs/2023-07-05/11-24-03",]
  csv_file_prev_run: [""]
  method: "random"
  num_frames: 10
  use_seeds: [0,1]
  iteration_folder: null

iteration_2:
  output_prev_run: []
  method: "random"
  num_frames: 10
  use_seeds: [0,1]
  iteration_folder: null



