project: "active_debug"

active_loop:
  current_iteration:
  experiment_cfg: "/data/libraries/lightning-pose/active_loop/configs/config_ibl_experiment.yaml"
  iterations_folder: "iteration_active_loop/experiment0" #relative to data_dir
  fast_dev_run: 1
  start_iteration: 0
  end_iteration: 3

iteration_x:
  output_prev_run:  # where the outputs of the last iteration are saved
  csv_file_prev_run:  # where the csv file of the last iteration is saved
  method: "random"  #active learning method
  num_frames:   # where the new frames are located

iteration_1:
  output_prev_run: # example: "/data/libraries/lightning-pose/outputs/2023-07-05/11-24-03"
  csv_file_prev_run: "../CollaectedData.csv"
  method: "random"
  num_frames: 10
  #csv_file:

iteration_2:
  output_prev_run:
  method: "random"
  num_frames: 10
  #csv_file:

iteration_3:
  output_prev_run:
  method: "random"
  num_frames: 10
  #csv_file:

